// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

import { getWebsiteContent } from "@/lib/websiteContent";
import ClientLayout from "./ClientLayout";
export const metadata: Metadata = {
  title: "restaurent-app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const content = await getWebsiteContent();

  const navbarProps = {
    logo: content?.site_settings?.logo,
    links: content?.navbar?.links,
    loginBtn: content?.navbar?.buttons?.login,
    registerBtn: content?.navbar?.buttons?.register_restaurant,
  };

  const footerData = content ? {
    brand: content.brand,
    columns: content.columns,
    socials: content.socials,
  } : null;

 return (
    <html lang="en">
      <body className="antialiased">
        <ClientLayout 
          navbarProps={navbarProps} 
          footerData={footerData}
        >
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}